### ISSUE TITLE
CosmosDB: Run SQL from Criteria

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1002]
# Bug Report

## Describe the Bug

It's possible to write SQL statement snippets in a `Criterion` and run them in Cosmos DB. For example to select everything use this `Criterion`:

```java
new Criterion("foo", "IN", "(1) OR 1=1 ")
```

The SQL snippet is inserted in a statement after the `WHERE` clause.

### Expected Behavior

SQL in a `Criterion` should be executed by CosmosDB queries.

### Observed Behavior

It's possible to write SQL in a `Criterion` at it's run from CosmosDB.

## Steps to Reproduce

Unit Test to reproduce
```java

    @Test
    void test_method() {

       /* Prepare CosmosDB with two assets */

        QuerySpec querySpec = QuerySpec.Builder.newInstance()
                .filter(
                        List.of(new Criterion("foo", "IN", "(1) OR 1=1 ")) // SELECT ALL
                )
                .build();
 
        List<Asset> assets = assetIndex.queryAssets(querySpec).collect(Collectors.toList());

        assertThat(assets).hasSize(2);
    }
}

```

## Context Information

At the time of writing this is difficult to abuse, as it's not possible to query a connector with a public API. Additionally CosmosDB only supports `SELECT` statements, so it won't be possible to execute `DROP` or `DELETE` statements.

As the query-code is in a library all queryable CosmosDB extensions should be affected.

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by paullatzelsperger** [comment]
I'm sorry but I'm struggling to comprehend what exactly the problem is. Is the problem that the Criterion allows for SQL statements to be added to the `rightOperand`? If that is not desired we'll have to have an explicit query language. To that end there is [this issue](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/323) which will constrain the query API and the types radically. 

Cosmos is not a relational database, it merely provides an SQL-like API for a document database, so `DROP` and `DELETE` will not work and that's by design.
