### ISSUE TITLE
HashiCorp Vault extension

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1026]
# Feature Request

It's time to support an OSS `Vault` implementation.

## Which Areas Would Be Affected?
`vault`

## Why Is the Feature Desired?
To being able to deploy the application on a K8s cluster without relying on external any (cloud) service.

## Solution Proposal
An extension module that provides an implementation for the `Vault.class` service interface.

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by bcronin90** [comment]
We just merged this feature in our downstream repository, since it was a priority for us. Please feel free to have a look at our implementation and we can determine what it would take to get this into the upstream EDC. Please note that it currently only supports Token Authentication for Hashicorp Vault.

You can find it [here]( https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault)
