### ISSUE TITLE
[Under discussion] Make tests verbose by default

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1049]
# Feature Request

#1018 ensures that tests are quiet by default, and a flag `-PverboseTest` was added to optionally make them verbose.

In the PR discussion it was suggested that tests should be verbose by default, and the flag should be reversed to optionally make them quiet. This issue exists to capture the discussion and agree on the way forward.

## Which Areas Would Be Affected?
Tests

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
thanks @algattik . As I reported in #1018 I think tests should be verbose by default, because I see to way of running tests (on my side):

- _from IDE_: probably launching one test or one test class most of the time, if the test is broken, some logs would be appreciated for sure, if every time need to launch a different test from the IDE I have to modify the "run configuration" and add the flag, it would become annoying.
- _from command line_: before push to verify that everything works correctly, probably logs in this case are not wanted, and would be straightforward to add a flag to shut them down, same on the CI.

**Comment by jimmarino** [comment]
My preference would be to have them as less verbose as possible when running from the command line. Currently, reams of useless information are output (e.g. runtimes starting up, etc.)

For the IDE case, more may be better. @ndr-brt can't you set a default environment variable for all your tests? That could be used to configure the monitor level and we could turn it down to info level.

Another improvement could be to implement a `Monitor` that redirects messages to the Gradle Logger.

**Comment by ndr-brt** [comment]
@jimmarino ` -PverboseTest` it's not an environment variable but it's a property. I don't know how to set a default one for the whole project making every test start with that property set. 
If anyone knows how to do it, please report here.

**Comment by algattik** [comment]
> @jimmarino ` -PverboseTest` it's not an environment variable but it's a property. I don't know how to set a default one for the whole project making every test start with that property set.

This is documented here https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties

**Comment by ndr-brt** [comment]
Seems like tests are verbose by default without adding any flag, at least from my IDE, will close this as it was opened because of me.
