### ISSUE TITLE
Inject default feature instance

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1056]
# Feature Request

In some parts of the codebase there are situations were a required feature needs to be injected with a default implementation if none provided, in these situations, the feature is marked as "not required" and then loaded with a default implementation like:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/3b7d17938562948e34522d4c919e725269ad0b8b/extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiExtension.java#L68-L72

Would be good to have a way to describe a required feature with a default implementation 

## Which Areas Would Be Affected?
extension loader, injector

## Why Is the Feature Desired?
To simplify the injection of a required feature with a default implementation fallback.

## Solution Proposal
The API on injection could look like:
```
@Inject(defaultImpl = NoopTransactionContext.class)
TransactionContext transactionContext;
```

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
@paullatzelsperger and I discussed this today. We came up with a different solution that does not require the client (injected) to have knowledge about the default implementation or whether a particular service has a default implementation or not.

We are thinking of adding the ability for an extension to declare "default provides" - i.e., that the extension can provide a default service if one is not provided by another extension. The behavior of this feature would be:

1. The default extension declares an optional @Inject field of the defaulted service type. The extension also declares that it "default provides" the service type via an annotation.

2. If no other extension provides the service, the default extension is instantiated, and the injected field will be null. The extension can check this and register the default implementation. 

3. If another extension provides the service, the default extension will be injected with the other implementation.

The runtime bootrapper will need to determine if an extension that provides a service implementation is configured for this to work. If it is not, the extension providing the default implementation will be used as the providing extension. If there is an extension configured that provides a service implementation, that extension will be used as the providing extension. In the latter case, the default extension will have a "requires" implicitly added that resolves to the other extension. This will guarantee proper extension ordering.

This mechanism will enable us to consolidate a number of extensions. Let's discuss this post-M3 since it is a bit late to introduce this type of change for M3.

**Comment by paullatzelsperger** [comment]
@ndr-brt I can take this on if that's ok for you

**Comment by ndr-brt** [comment]
@paullatzelsperger I already have a solution that at least solves the duplication issue and also the `ExecutorInstrumentationImplementation` issue, currenty the solution requires the client to specify the default implementation (as I specified in the issue), 
but I noticed that this default declaration could be moved on the `@Feature` annotation, so the default instance is specified by the feature directly, so the clients couldn't need to worry about the default implementation.

I would open this PR as a first step to go in the direction of the 3 points specified by @jimmarino if you agree.

**Comment by ndr-brt** [comment]
@paullatzelsperger Why don't let the `@Feature` being able to define a default implementation instead of having a "default extension" to do so? It seems simpler and it covers all the cases currently present in the codebase.

**Comment by paullatzelsperger** [comment]
For one, because that would introduce a downstream dependency, for example `TransferProcessStore` is located in `transfer-spi`, but the default implementation (=in-mem) would either be located in a separate module, or potentially in the corresponding module in core, thus `:core:transfer`. Therefore, suddenly `:spi:transfer-spi` has a dependency on either of those two.

The second reason is, that @bscholtes1A and I were actually conspiring to remove the `@Feature` annotation altogether, as it is merely an alias for the class name, which is the default already.

**Comment by ndr-brt** [comment]
Got it, I can work on this since I'm already on it

**Comment by jimmarino** [comment]
@paullatzelsperger @ndr-brt How about removing @Feature entirely?

**Comment by ndr-brt** [comment]
Superseded by #1130
