### ISSUE TITLE
ids-messaging: Add aditional validations

### ISSUE THREAD

**Issue by juliapampus** [eclipse-dataspaceconnector/DataSpaceConnector#1152]
# Feature Request

The ids messaging could be improved by extending the validation of incoming messages.

## Which Areas Would Be Affected?
ids multipart handler

## Why Is the Feature Desired?
Prevent identity theft and IDS infomodel incompatibilities.

## Solution Proposal
This list could be extended:
- [ ] Compare DAT claims to message values (e.g. referringConnector == issuerConnector; check hostname of incoming request)
- [ ] Check IDS Infomodel version against inbound versions

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by sebbader** [comment]
I propose SHACL for the second task (Check IDS Infomodel version against inbound versions). The IDS IM ships with SHACL schemas (aka shapes) out of the box, and there is a pretty widely used open source library: https://github.com/TopQuadrant/shacl

**Comment by tmberthold** [comment]
For the (dat-)`referringConnector` == (message-)`issuerConnector` and `hostname` validation, please watch out for Catena-X, because the DAT claim is currently used for the BPN at the moment

https://github.com/catenax-ng/product-edc/blob/1708db02372a2e85ec6e888ecbd3efeae9139b9b/edc-extensions/business-partner-validation/src/main/java/net/catenax/edc/validation/businesspartner/functions/AbstractBusinessPartnerValidation.java#L85

**Comment by SebastianOpriel** [comment]
If a BPN instead of the connectors URL is used for referringConnector field, *no interoperability with other data spaces* will be possible. Or another service must be present, which allows a lookup of further details.
I ask myself how EDC in case of using BPN is able to avoid DAT reply attacks.
