### ISSUE TITLE
DPF: public API input validation

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#1163]
# Feature Request
`DataPlanePublicApiController` provides an endpoint that is accessible from 'the world outside'.
The data plane should provide at least some basic mechanisms to protect itself against fraudulent or accidental broken calls, e.g. limit the size of the body, path, query params etc.
Some basic checks are sufficient. More sophisticated checks can always be done as part of an ingress controller, WAF, proxy, .... placed before the endpoint - if needed.

## Which Areas Would Be Affected?
DPF

## Why Is the Feature Desired?
protect service

## Solution Proposal
define max body size (config value with sensible default)
max size for URL parts

## Type of Issue
improvement

**Comment by ndr-brt** [comment]
Jetty by default already provides limit for them: 

- "request header size", that's the limit for the header size of a request, it's set to 8KB by default:
https://github.com/eclipse/jetty.project/blob/cb127793e5d8b5c5730b964392a9a905ba49191d/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java#L57

- "form content size", that's the limit for the body, it's set to 200000 by default (less than 200KB):
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L146

So this issue can be closed in my opinion, unless we want those parameters configurable, but that would be a different issue.

**Comment by MoritzKeppler** [comment]
thanks for the investigation @ndr-brt!

Definitely good to know that Jetty comes with some useful defaults (even if one could argue that it would be better to set values explicitly and not trust other libs to be configured properly)

If I got it right the max form content size is just used when parsing params from a http body that contains form values and has no influence on the number of bytes we read in  `ContainerRequestContextApiImpl`.

Suggest to at least add some lines to the README of the extension describing what can be configured to protect the dataplane / what needs to be done in the infrastructure added in front of the dataplane.

<sub> Moritz Keppler <moritz.keppler@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by ndr-brt** [comment]
@MoritzKeppler I dived deep into this, apparently, the `request header size` is working fine, while the `max form content size`, as the name speaks, limits only the form requests.

According [to this reply on stackoverflow](https://stackoverflow.com/a/49257223/7305670) (that can't be considered an undeniable truth, but at least it's a starting point), for **All other request Content-Type entries**:
> For all other Content-Type values, the servlet spec, and Jetty are not involved in parsing or limiting the size.
> If you are using a library to handle your requests (REST, SOAP, etc) then check with that library to see if it has a mechanism to reject requests based on size, or other reasons (eg: not well-formed, missing expected/required data, etc).

so in this case we would need to implement a custom validation on `DataPlanePublicApiController`.
My question is, since the requests that pass through the `DataPlanePublicApiController` are made by a verified dataspace participant (so not-malicious by definition) do we really need a limit here? If it is to improve performances and avoid OOM errors could we refactor the data plane to handle streams instead of having to mapping the input stream body to a string and back?

**Comment by MoritzKeppler** [comment]
I would argue for following the old security principle and never trust any caller. As described before I'm also fine with just having a section in the Readme that describes how the dataplane can be operated in a secure way (e.g. "limit size of body in a proxy placed before").
Using a stream could also be an option to reduce the risk for the connector (maybe instead increasing the risk for the service in the background) - but maybe better invest in #1121

**Comment by juliapampus** [comment]
Documentation to be added @ndr-brt
