### ISSUE TITLE
Support latest version IDSA/Fraunhofer DAPS (omejdn-daps) 

### ISSUE THREAD

**Issue by newinnovations** [eclipse-dataspaceconnector/DataSpaceConnector#1395]
# Bug Report

## Describe the Bug
Not a bug per se, but the IDS DAPS module (:extensions:iam:daps) only supports older versions of the IDSA/Fraunhofer omejdn-server. The integration testing is done against version 1.2.1. The latest working version is 1.4.2.

An other issue is that testing is done against the bare omejdn-server, better would be to test against the full DAPS (https://github.com/International-Data-Spaces-Association/omejdn-daps)

### Expected Behavior
... is to support the latest and greatest (currently 1.6.1)
 
### Observed Behavior
Tests fail against version 1.5.0 onwards.

## Steps to Reproduce
Working:
```docker run --rm -p 4567:4567 -v $PWD/extensions/iam/daps/src/test/resources/config:/opt/config -v $PWD/extensions/iam/daps/src/test/resources/keys:/opt/keys ghcr.io/fraunhofer-aisec/omejdn-server:1.2.1```

Not working:
```docker run --rm -p 4567:4567 -v $PWD/extensions/iam/daps/src/test/resources/config:/opt/config -v $PWD/extensions/iam/daps/src/test/resources/keys:/opt/keys ghcr.io/fraunhofer-aisec/omejdn-server:1.6.1```

Run test:
```./gradlew clean :extensions:iam:daps:test -DincludeTags="DapsIntegrationTest"```

## Possible Implementation
Root cause seems to be related to changed locations of the keys and the well known JWKS location.

**Comment by bellebaum** [comment]
A bit of background:

The DAPS is based on regular OAuth 2.0, which (in some extensions) makes use of a JWKS. There is no specified location for this, and many OAuth Authorization Servers choose their own locations. (See e.g. [Paypal](https://api.paypal.com/v1/oauth2/certs) or [GoogleAPIs](https://www.googleapis.com/oauth2/v3/certs)). Typically the user of such a system were expected to read the service description provided by the Authorization Server Operator and configure their clients accordingly.
The modern solution provided by OAuth is [RFC 8414](https://datatracker.ietf.org/doc/rfc8414/). Essentially:

Given an issuer identifier URL (Say, `https://daps.aisec.fraunhofer.de/v3`), prepend `/.well-known/oauth-authorization-server` to the path component (Example: https://daps.aisec.fraunhofer.de/.well-known/oauth-authorization-server/v3). You will find there a JSON document that includes a member `jwks_uri`. That is the URL to find the JWKS. You can also use this to find the `token_endpoint` to get a DAT, if you want to spare your users some configuration.

There is also a proposal to add this to IDS-G, so this method should be quite future-proof and I would recommend implementing it. The DAPS reference implementation Omejdn already supports it, so I would suggest using it here too.
If, for whatever reason, you would not like to implement this, an easy way of providing compatibility is to let the users choose the jwks_uri via some configuration.

Since IDS-G currently has `.well-known/jwks.json` written into it, I will also add a temporary rewrite directive to the default nginx-configuration for the omejdn-daps repo.

**Comment by gbrost** [comment]
We are currently sketching an approach and will find someone to contribute (maybe in addition to Thomas).
