### ISSUE TITLE
Refactor TokenResult

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#140]
Hello everyone,

currently the TokenResult looks like this
```java
public class TokenResult {

    /**
     * Returns true if the flow was successful.
     */   
    boolean success() {
        ...
    }


    /**
     * Returns the bearer token if the flow was successful; otherwise null.
     */
    public String getToken() {
        ...
    }

    /**
     * Returns the token expiration.
     */
    public long expiresIn() {
        ...
    }


    /**
     * Returns the error details if the flow was not successful; otherwise null.
     */
    public String error() {
        ...
    }

}
```

I'd suggest we make the following two changes. 

1. The TokenReuslt should not have an success() and error() method. I'd like it more if the functions, that create the result, would throw an exception in case an error occurs.
2. The expiresIn is difficult to use, as it is now, because the code that want to check the expiration needs to know then the TokenResult was created. An internal expirationDate with a getter and an isExpired() method would work better.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
I don't think we should use exceptions for flow control. If an unexpected exception occurs, it should throw an unchecked one, extending from EdcException if there is not an appropriate exception in the JDK.

Error is for things like invalid tokens or other "problems".

This is a general pattern we use throughout the codebase.

We need to be careful with expiresId being a fixed date. How will time zones be handled?

**Comment by jimmarino** [comment]
Sorry, to clarify, I'm not talking about ignoring unexpected exceptions and returning booleans. The TokenResponse error is when there is something about the request that is in "error" (hence the term "error" instead of exception).

If there is an unexpected exception, it could be thrown (as an unchecked exception, which the codebase standardizes on). However, this must be done with care to avoid exceptions leaking security-related information. If something needs to be logged/handled in this sensitive part of the code that may potentially contain sensitive information, it should be done at that point and not leave it to code higher up in the stack. As background, we spent a lot of time on this when we did a security audit of the codebase in this area.

Since this is all abstract, let me ask a specific question: what problem are you attempting to address in the current codebase?

On the timezone question, I'm not against changing "expiresIn", but if you specify a fixed time, you need to have a strategy for handing timezones.

**Comment by jimmarino** [comment]
Closing as I believe these questions have been addressed.
