### ISSUE TITLE
api: verbose response body error messages

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1411]
# Feature Request

Sometimes it's hard to understand why an API request fails, as in the body there are no details about what happened.
Would be useful to have a configuration setting to enable a verbose request body in these cases.
By default this should be off as it is not recommended in a production environment to give such details to the outside.

## Which Areas Would Be Affected?
api

## Why Is the Feature Desired?
To help debug

## Solution Proposal
`EdcApiExceptionMapper` is a place where all the exceptions thrown in the api context are handled. 
Should be enough to put the `Result` object into the `EdcApiExtension` and if a particular setting is enabled, the error detail could be included in the body.
Should worth how to make also `jakarta-validation` exceptions pass through this, as I don't think they currently do this (needs further investigation).
If the "verbose response body" setting is enabled, a warning at startup should be printed.

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
@florianrusch-zf @tuncaytunc-zf FYI

**Comment by jimmarino** [comment]
I'm not sure about having a separate debug setting for this. If there is a problem, it seems the server should return enough information for the client to understand what the issue is, even in a production deployment. 

Is there a concrete example we could walk through where the client would need more information than is appropriate to send back in a production environment?

**Comment by ndr-brt** [comment]
@jimmarino the idea was to avoid giving information to eventual malicious third party systems about how to get their call more effective.

**Comment by florianrusch-zf** [comment]
@jimmarino For example deleting a policy could lead in two cases to a 409 statuscode without any information. A not edc contributor person doesn't know in this case, why he receives a 409 because there is not log entry or any information in the response what's going wrong.

This case was already described here: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1332
