### ISSUE TITLE
HTTP Based Download as part of Eclipse DataSpace Connector?

### ISSUE THREAD

**Issue by sn0wcat** [eclipse-dataspaceconnector/DataSpaceConnector#143]
A common scenario for integration of the existing systems with data spaces would be to offer files for download. 

The following diagram showcases an integration with a s3 based software which was working with the previous versions of the connector (IDC)

![image](https://user-images.githubusercontent.com/1426617/136923084-64a147ad-a06c-412e-9f83-fe22bf61f139.png)

How is this going to work with EDC? Will the http download be part of connector, or will this have to be out-of-band extension?

**Comment by jimmarino** [comment]
Thanks for the diagram, it is helpful. 

A couple questions:

1. Is each artifact contained in a single file? I ask because I seem to remember that AWS temporary URLs are assigned to a file.
2. Per @beardyinc comments, how is the client going to obtain the download? For example, manually or via a process initiated by the client connector?
