### ISSUE TITLE
Add @Provides Method to CommonsConnectionPoolServiceExtension

### ISSUE THREAD

**Issue by mark-olchanski** [eclipse-dataspaceconnector/DataSpaceConnector#1759]
We are currently experiencing problems when implementing the SQL data-store classes. The issue arises due to the loading order of our implementations. The SQL stores are loaded first (having no `DataSource` loaded in its `DataSourceRegistry` at this stage), then our own extensions are loaded, followed by the `apache-commons-pool-sql` module.

Our extensions try to save a dummy-policy and `contractDefinition`. This, however, does not work since the `dataSource` registration (performed inside `CommonsConnectionPoolServiceExtension`) is loaded last.

A fix to this would be to add a `@Provides({ ConnectionPool::class })` to the `CommonsConnectionPoolServiceExtension`, so that we could add a `@Requires` annotation to our extension.

**Comment by paullatzelsperger** [comment]
Right off the bat, using `@Provides` and `@Requires` for this feels like a bit of a misuse, because (strictly speaking) it was intended to sort dependencies that are registered with the `ServiceExtensionContext`.

However, as you pointed out, it would still solve the problem here, and semantically it would be acceptable too. Let me look into it and investigate some options.

**Comment by mark-olchanski** [comment]
Thank you for the quick reply!

I tried your suggestion with the `start()` method and this seems to do the trick, so far everything works :)
