### ISSUE TITLE
Connector accepts **any** Contract Offer

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1791]
# Bug Report

## Describe the Bug
A connector accepts any contract offers. The content of the contract offer is not checked.

=> It is possible to change a contract in any way. It is not possible to create a contract for assets, the connector would not have access to. 

### Expected Behavior

- Connector accepts only contracts it has offered before.

### Observed Behavior

- Connector accepts **any** contracts.

## Steps to Reproduce
1. Connector_A: Create Asset

```json
{
  "asset": {
    "properties": {
      "asset:prop:id": "1"
    }
  },
  "dataAddress": {
    "properties": {
      "type": "HttpData",
      "baseUrl": "<url>"
    }
  }
}
```

3. Connector_A: Create Policy

```json
{
  "uid": "1",
  "policy": {
    "permissions": [
      {
        "edctype": "dataspaceconnector:permission",
        "action": {
          "type": "USE"
        },
        "constraints": [
          {
            "edctype": "AtomicConstraint",
            "leftExpression": {
              "edctype": "dataspaceconnector:literalexpression",
              "value": "Pay_Me"
            },
            "rightExpression": {
              "edctype": "dataspaceconnector:literalexpression",
              "value": "1000 Euros"
            },
            "operator": "EQ"
          }
        ]
      }
    ]
  }
}
```

4. Connector_A: Create Contract Definition

```json
{
  "id": "1",
  "criteria": [
    {
      "operandLeft": "asset:prop:id",
      "operator": "=",
      "operandRight": "1"
    }
  ],
  "accessPolicyId": "<something public>",
  "contractPolicyId": "1"
}
```

4. Connector_B: Initiate contract negotiation via POST at `/contractnegotiations` API, but does not want to pay (leaves the constraints out).

```json
{
  "connectorId": "foo",
  "connectorAddress": "${Connector_A}/api/v1/ids/data",
  "offer": {
    "offerId": "1:foo",
    "assetId": "1",
    "policy": {
      "uid": "2",
      "permissions": [
        {
          "edctype": "dataspaceconnector:permission",
          "action": {
            "type": "USE"
          },
          "target": "1",
          "constraints": []
        }
      ]
    }
  }
}
```

5. Check contract agreement in database of Connector_A

| agr_id | asset_id | policy |
|:---|:---|:---|
|1:6e9e400c-a411-4cef-8135-047ffd532061 | 1 | {"permissions":[{"edctype":"dataspaceconnector:permission","uid":null,"target":"1","action":{"type":"USE","includedIn":null,"constraint":null},"assignee":null,"assigner":null,"constraints":[],"duties":[]}],"prohibitions":[],"obligations":[],"extensibleProperties":{},"inheritsFrom":null,"assigner":null,"assignee":null,"target":null,"@type":{"@policytype":"set"}} |

## Context Information

- Used version: Milestone 5

## Detailed Description

Catalog from Connector_A:

```json
{
  "id": "default",
  "contractOffers": [
    {
      "id": "1:95cab8a1-b3c5-4d59-b8b7-f8fcc6e4697f",
      "policy": {
        "permissions": [
          {
            "edctype": "dataspaceconnector:permission",
            "uid": null,
            "target": "1",
            "action": {
              "type": "USE",
              "includedIn": null,
              "constraint": null
            },
            "assignee": null,
            "assigner": null,
            "constraints": [
              {
                "edctype": "AtomicConstraint",
                "leftExpression": {
                  "edctype": "dataspaceconnector:literalexpression",
                  "value": "Pay_Me"
                },
                "rightExpression": {
                  "edctype": "dataspaceconnector:literalexpression",
                  "value": "1000 Euros"
                },
                "operator": "EQ"
              }
            ],
            "duties": []
          }
        ],
        "prohibitions": [],
        "obligations": [],
        "extensibleProperties": {},
        "inheritsFrom": null,
        "assigner": null,
        "assignee": null,
        "target": null,
        "@type": {
          "@policytype": "set"
        }
      },
      "asset": {
        "properties": {
          "asset:prop:description": "Product EDC Demo Asset",
          "ids:byteSize": null,
          "asset:prop:id": "1",
          "ids:fileName": null
        }
      },
      "assetId": null,
      "provider": "urn:connector:provider",
      "consumer": "urn:connector:consumer",
      "offerStart": null,
      "offerEnd": null,
      "contractStart": null,
      "contractEnd": null
    }
  ]
}
```

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
Currently the EDC does not support a full contract agreement, so every consumer request with a policy that differs from the offered one should be declined by the provider.

At a first glance this seems a check to be added to the `ContractValidationService`, if the policy referred by the contract definition is not equal to the offered one, the contract should not be valid.

**Comment by ndr-brt** [comment]
The issue here is how to ensure this "equality", there are some issues:
1. what equality use, the quick solution would be to override the `equals` method for every policy model class
2. the `Policy.target` field, that is valued by the `ContractOfferServiceImpl` with the `assetId`, but then when is passed to the consumer through the catalog, it went lost because `ContractOfferToIdsContractOfferTransformer` does not map it to any field of the `ids:ContractOffer` object (that has no `target` field). Is this `target` field useful to anyone? According to the [ODRL model](https://www.w3.org/TR/odrl-model/#policy):
> An ODRL Policy MAY also declare properties which are shared and common to all its Rules. Specifically; action properties, sub-properties of relation (such as target), and sub-properties of function (such as assigner and assignee).

In particular, [seems like](https://www.w3.org/TR/odrl-model/#composition-compact):
> An ODRL Policy MAY hold properties, declared at the Policy-level, which are shared and common to all its Rules. This is aimed only as a short-cut method to support more compact serialisations. These shared properties MUST NOT be interpreted as Policy-level properties (such as those defined in the [Policy Class](https://www.w3.org/TR/odrl-model/#policy) section).

So some fields on `Policy` derive from unique values on the `Rule`s, and that's another thing we need to take care of while checking for equality

**Comment by paullatzelsperger** [comment]
it sounds like interpreting the Policy with regards to these "shared properties" is going a bit beyond what is needed here.

For the sake of simplicity: can we establish the constraint that two Policies must be absolutely _identical_ in order to be considered _equal_? That would not be 100% correct in an ODRL-sense, but would make things easier now. That means, ignore the `Policy.target` field entirely for now.

In the future, we can expand the equality check to take into account these shared properties. And by that time I would also expect the improvements to IDS to be in place.

**Comment by ndr-brt** [comment]
After a discussion on the PR #1817 I discovered that actually this is not a bug, because a the policy sent by the consumer is completely ignored: 
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/5ae18f3ab7b9c109e5d81c75c8e03d94b3913387/core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java#L76-L103

So this "malicious" behavior cannot happen. The doubt here is: is it correct that the consumer sends a policy but at the end the negotiation will contain another policy?
