### ISSUE TITLE
Filter catalog by assets properties

### ISSUE THREAD

**Issue by maciejkizlich-zf** [eclipse-dataspaceconnector/DataSpaceConnector#1966]
# Feature Request

catalog-api now supports 'filter' query param, but it's not being passed via ids-api. The logic for ACTUAL filtering by such filters is already in place.

## Which Areas Would Be Affected?
catalog-api, ids

## Why Is the Feature Desired?
To allow filtering catalog response by assets properties, eg. asset:prop:type, etc.

## Solution Proposal
The idea is to pass filtering query along with range (limit + offset):

[MultipartCatalogDescriptionRequestSender.buildMessageHeader()](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartCatalogDescriptionRequestSender.java)

and handling it in:

[DescriptionRequestHandler.handleRequest()](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandler.java)

## Type of Issue
new feature/improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by florianrusch-zf** [comment]
@jimmarino do you have any information for us on when the definition will start and when it is expected to be finished? Catena-X asks about this feature

**Comment by maciejkizlich-zf** [comment]
@jimmarino what do you say if we wanted to fix this anyway in the current protocol implementation, so people can use the feature right away?

**Comment by paullatzelsperger** [comment]
@maciejkizlich-zf from what I saw the change should be rather limited in scope. Before submitting any implementation PR please provide a decision record (also as a PR), that outlines the following:
- "Decision": what is the proposed change
- "Rationale": motivation of the proposed change, i.e. why it is necessary ("because people want it" is not sufficient. It's important to understand _why_ people want it)
- "Approach": the impact on the code base. which areas of code would be affected, what's your approach, what would you change and how, how would testing have to be adapted, etc.

Please be succinct and brief, D-Rs should be fairly compact in size.

**Comment by maciejkizlich-zf** [comment]
@paullatzelsperger thanks, I'll prepare the DR then.

**Comment by maciejkizlich-zf** [comment]
@paullatzelsperger @jimmarino @florianrusch-zf @ndr-brt 

Please find said DR here:

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1983
