### ISSUE TITLE
make `MockIdentityService` a default service

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#2042]
# Feature Request

currently, to run a simple instance of the connector, is mandatory to define a `iam` module (like the `iam-mock`, for testing purposes), this could be more user friendly registering the `MockIdentityService` or a simple noop version of the `IdentityService` by default and printing out a warning (like already done with `TransactionContext` and `AuthenticationService`.

## Which Areas Would Be Affected?
core

## Why Is the Feature Desired?
improve developer experience

## Solution Proposal
-

## Type of Issue
improvement

**Comment by jimmarino** [comment]
I think we need to be really careful with this. If we have a mock service, we should set it to fail validation until it is configured to explicitly enable all validation. In a test environment, this configuration could be done by default but from the command line launcher, it could be a requirement for the operator to explicitly enable.

**Comment by jimmarino** [comment]
IMO, this is a different category. The other default providers, such as the default trx context provider, may cause the runtime not to work correctly, but they won't necessarily lead to compromised security. 

What I am proposing is a solution that will keep things simple. For the samples, the behavior can relax security controls by having explicit configuration enable the default provider to pass validation. However, the behavior when the configuration is not set should be to fail validation. If the configuration is not specified, the monitor can also issue a warning to indicate that the default provider is engaged and may need to be explicitly configured.

I don't see any real advantage to having validation always pass since a monitor message instructing developers to enable it is easy to follow. It also avoids a potentially significant security issue.
