### ISSUE TITLE
Use Serializer instead of ObjectMapper for Infomodel objects

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-dataspaceconnector/DataSpaceConnector#236]
In the IDS modules the class `de.fraunhofer.iais.eis.ids.jsonld.Serializer` should be used to map Infomodel objects to and from JSON. Currently, an ObjectMapper is used to perform these operations. Thus, the required context information is missing in the JSON and it cannot be deserialized by an Infomodel serializer.

Also, the MultipartController takes a RequestMessage as parameter, so that the header part is automatically mapped to a RequestMessage object upon request. This mapping should also be performed by the Infomodel serializer.

**Comment by jimmarino** [comment]
A couple of questions:

1. Is that class part of a library on Maven central and do you know its license?

2. For my own knowledge, which context info do we need from the endpoints that the ObjectMapper will not provide? It looks as if the Serializer uses an ObjectMapper internally

Thx.

**Comment by denisneuling** [comment]
@jimmarino, The artifact is served by [Fraunhofer IAIS maven repo](https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel-serializer/). Although the [sources](https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel-serializer/4.0.0/infomodel-serializer-4.0.0-sources.jar) are publicly available the artifact does not contain any licensing information neither within the JAR nor in the source code files itself, so we have to assume default copyright laws apply until it is added.

As you already mentioned the `Serializer` seems to be built around [Jackson's ObjectMapper](https://fasterxml.github.io/jackson-databind/javadoc/2.13/com/fasterxml/jackson/databind/ObjectMapper.html) to amend the [JSON-LD @context token](https://json-ld.org/spec/latest/json-ld/#syntax-tokens-and-keywords) to serialized payloads.

Each IDS struct needs to be introduced by the `ids` and `idsc` context: 
```json
"@context": {
  "ids": "https://w3id.org/idsa/core/",
  "idsc": "https://w3id.org/idsa/core/"
}
```

Whereas the [DatPayload](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#DatPayload)'s `@context` in addition receives `ids:referringConnector`, `ids:aud`, `ids:iss`, `ids:sub`, `ids:nbf`, `ids:exp`, `ids:iat`:

```json
"@context": {
  "ids": "https://w3id.org/idsa/core/",
  "idsc": "https://w3id.org/idsa/core/",
  "ids:referringConnector": "https://w3id.org/idsa/core/",
  "ids:aud": "https://w3id.org/idsa/core/",
  "ids:iss": "https://w3id.org/idsa/core/",
  "ids:sub": "https://w3id.org/idsa/core/",
  "ids:nbf": "https://w3id.org/idsa/core/",
  "ids:exp": "https://w3id.org/idsa/core/",
  "ids:iat": "https://w3id.org/idsa/core/"
}
```

IMO we should implement this ourselves, since it doesn't seem to be to complex and we shouldn't wait until the licensing has been clarified / made permissive. What do you think?

Will submit a PR introducing a new gradle module providing the de/serialization functionality during the day.

**Comment by jimmarino** [comment]
> @jimmarino, The artifact is served by [Fraunhofer IAIS maven repo](https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel-serializer/). Although the [sources](https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel-serializer/4.0.0/infomodel-serializer-4.0.0-sources.jar) are publicly available the artifact does not contain any licensing information neither within the JAR nor in the source code files itself, so we have to assume default copyright laws apply until it is added.
> 
> As you already mentioned the `Serializer` seems to be built around [Jackson's ObjectMapper](https://fasterxml.github.io/jackson-databind/javadoc/2.13/com/fasterxml/jackson/databind/ObjectMapper.html) to amend the [JSON-LD @context token](https://json-ld.org/spec/latest/json-ld/#syntax-tokens-and-keywords) to serialized payloads.
> 
> Each IDS struct needs to be introduced by the `ids` and `idsc` context:
> 
> ```json
> "@context": {
>   "ids": "https://w3id.org/idsa/core/",
>   "idsc": "https://w3id.org/idsa/core/"
> }
> ```
> 
> Whereas the [DatPayload](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#DatPayload)'s `@context` in addition receives `ids:referringConnector`, `ids:aud`, `ids:iss`, `ids:sub`, `ids:nbf`, `ids:exp`, `ids:iat`:
> 
> ```json
> "@context": {
>   "ids": "https://w3id.org/idsa/core/",
>   "idsc": "https://w3id.org/idsa/core/",
>   "ids:referringConnector": "https://w3id.org/idsa/core/",
>   "ids:aud": "https://w3id.org/idsa/core/",
>   "ids:iss": "https://w3id.org/idsa/core/",
>   "ids:sub": "https://w3id.org/idsa/core/",
>   "ids:nbf": "https://w3id.org/idsa/core/",
>   "ids:exp": "https://w3id.org/idsa/core/",
>   "ids:iat": "https://w3id.org/idsa/core/"
> }
> ```
> 
> IMO we should implement this ourselves, since it doesn't seem to be to complex and we shouldn't wait until the licensing has been clarified / made permissive. What do you think?
> 
> Will submit a PR introducing a new gradle module providing the de/serialization functionality during the day.

Makes sense to me. If there is no license, we can't use it anyway.

**Comment by denisneuling** [comment]
Seems it's not done by just adding the `@context`. All properties in the payload have to be exploded and denoted by it's JSON-LD `@type`. 

Instead of - as its currently implemented - producing this exemplary payload:
```json
{
  "@type" : "ids:DescriptionResponseMessage",
  "@id" : "urn:message:470213d9-ea4c-4d9e-a3a5-240fb42e53ba",
  "ids:issued" : "2021-11-16T07:34:15.029UTC",
  "ids:issuerConnector" : "urn:connector:2dfd66c9-7a75-4024-9713-2286be86bee3",
  "ids:senderAgent" : "urn:connector:2dfd66c9-7a75-4024-9713-2286be86bee3",
  "ids:correlationMessage" : "https://w3id.org/idsa/autogen/descriptionRequestMessage/4f0b748f-b402-45f8-b3fc-7599ef10aa62"
}
``` 

this one is rather expected:
```json
{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/"
  },
  "@type" : "ids:DescriptionResponseMessage",
  "@id" : "urn:message:63c6422d-b074-4d16-a507-ea26b26806b5",
  "ids:issued" : {
    "@value" : "2021-11-16T08:35:59.762+01:00",
    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
  },
  "ids:issuerConnector" : {
    "@id" : "urn:connector:a3d04f56-c8e2-462d-8b87-fcf4e76b0b86"
  },
  "ids:senderAgent" : {
    "@id" : "urn:connector:a3d04f56-c8e2-462d-8b87-fcf4e76b0b86"
  },
  "ids:correlationMessage" : {
    "@id" : "https://w3id.org/idsa/autogen/descriptionRequestMessage/8539c32e-39fb-41ba-bdec-e7747179311f"
  }
}
``` 

Unfortunately this will take me some time to implement the proper serialialization/deserialization strategy since the issue became a little more complex...

**Comment by sebbader** [comment]
Hello everyone, we are providing the JSON-LD Serializer for the IDS projects. 
"If there is no license, we can't use it anyway." 
This shouldn't be a show stopper. Which licenses would be feasible for you to continue here?

**Comment by denisneuling** [comment]
Hello @sebbader, many thanks for reaching out.
Glad to hear you are considering changing the license of the JSON-LD serializer to let us make use of it.
It would be awesome if you could serve it under the [Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0) license.

**Comment by jimmarino** [comment]
@sebbader Thanks for getting in touch. It looks like the Serializer (3.1.1) brings in the following dependencies

1. javax.validation
2. SLF4J
3. org.eclipse.rdf4j.json-ld
4.  rdf4j-rio-turtle
5. rdf4j-rio-rdfxml

Based on this, I have a few questions:

1. Are those needed, particularly 1,2, 4, and 5? 
2. If so, can they be removed or made optional? 
3. What IDS infomodel does this library work with? 
4. Is the source available as open-source (separate from the license)?

In order to use this module, it would first have to be published to Maven central under the Apache license.

Thanks and sorry for the barrage of questions!

**Comment by jimmarino** [comment]
@denisneuling To simplify things for the December milestone, can we leave out the JSON-LD metadata from the serialized forms? For our purposes, we don't need it. In the meantime, we can continue the discussions on licensing, dependencies, etc.

**Comment by sebbader** [comment]
@jimmarino "can we leave out the JSON-LD metadata from the serialized forms?" --> As a Linked Data believer, that really hurts! :-)

**Comment by sebbader** [comment]
Regarding the points you have raised:
> 1. Are those needed, particularly 1,2, 4, and 5?
I need to check with my team before I can answer.

> 2. What IDS infomodel does this library work with?
Always the latest. Meaning, every major or minor release is one-to-one represented (IM version 4.2.0 is reflected by serializer/java model versions 4.2.x and so on). We provide continuous builds for all features of the IM and work very closely with the SWG Information Model. Actually, those two libs are the reference implementations of the IM.

> 4. Is the source available as open-source (separate from the license)?
Not a problem to do so. For now, there was no necessity to go the extra mile for a real open source setting. But that's only a question of time and capacity and not of IP restrictions.

**Comment by bscholtes1A** [comment]
Note that this issue is blocking for the Pull Data transfer part when using the public data plane API, see [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/585). Here the Contract is checked in order to ensure that the consumer still has access to the data, which implies to check if the contract end date is not yet overdue. 
With current implementation this is not possible as end date is not present in the contract.

**Comment by DominikPinsel** [comment]
The original pull-request #730 was somehow problematic. I assume the problem was that it was expected to be a simple serializer exchange.

Therefore I would suggest to create extra PR for each non-IDS-compliant message we create (which are basically all IDS messages we create).
The IDS-Serializer validates whether the messages are IDS compliant, therefore we need these message compliant before the serializer is integrated. I'd suggest to create a factory, wrapping the IDS builders, that only creates compliant messages. Like this we can ensure that there will be no issues when the serializer is integrated, before integrating the serializer itself.

Additionally there were some minor issues like invalid URIs or dates in the IDS messages. I suggest creating an extra PR for each issue here, too.

To keep the changes to a minimum and to avoiding rejected PRs again I would not create new PR for some minor improvements in the original PR. Like changing the connector ID from String to URI for type safety in the future, renaming EDC classes to have different names than IDS and avoid confusion, or moving information out of the IDS properties, which are annotated with JsonIgnore and not always serialized.

When all this is done I will create a PR for the serializer exchange, which should be simple by then.

WDYT? @jimmarino  @juliapampus

**Comment by juliapampus** [comment]
Further actions regarding IDS implementations in the EDC are expected to be documented in a decision record.
