### ISSUE TITLE
Add another sample focusing on the Contract Negotiation piece

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#361]
Sample 04 focuses on data transfer from one directory to another, whereas Sample 05 is the fully-fledged behemoth showcasing deployment and cross-cloud transfers. There is quite a big continuity gap between those two in terms of understanding the connector.

Thus the following things must be done:
- [x] Make sure that the documentation of sample 4 outlines that connectors are intended to run on different machines/clusters, and that the file transfer is a mere placeholder, chosen for simplicity. (@paullatzelsperger) -- fixed by PR #372 
- [x] Re-work sample 4 to contain contract negotiation (@ronjaquensel)
- [x] add/adapt documentation (@ronjaquensel)
- [x] add a job to the sanity check job in `verify.yaml` (@ronjaquensel)

Linked to #246

**Comment by paullatzelsperger** [comment]
we will have to backport this to sample 4 as well, because using IDS Multipart, every data transfer requires a `ContractAgreement`.

**Comment by ronjaquensel** [comment]
True, if we wanna remove IDS Rest from sample 4, which makes sense. Then the new sample would actually replace sample 4 instead of sample 5, right? I think once we add contract negotiation to sample 4 and integrate IDS multipart, we're basically already at the new sample. But then we'll have a rather big gap between sample 3 and 4, unless we want to make a sample that performs contract negotiation but doesn't do any data transfer.

**Comment by paullatzelsperger** [comment]
I think IDS Rest will get deprecated and ultimately be removed (cf. PR #367), so we really have little choice. Doing contract negotiation without a transfer sounds a bit ... artificial. 
I'd rather have the big gap. So IMO we can add Contract Negotiation to Sample 4 (and also Sample5), document it well and be done with it.

**Comment by ronjaquensel** [comment]
@paullatzelsperger fine by me, then I'll just replace the current sample 4 with the new one.
