### ISSUE TITLE
SDK usage - Useful - More extensive implementation of Builders

### ISSUE THREAD

**Issue by Izzzu** [eclipse-dataspaceconnector/DataSpaceConnector#424]
More extensive implementation of Builders could help when writing test code.

Suggestions to consider:
- Using _toBuilder_ functionality (it’s an instance method that creates a new builder starts out with all the values of this instance, helpful with creating test data, this functionality is available in a [builder offered by Lombok framework](https://projectlombok.org/features/Builder)).
- Using [Lombok](https://projectlombok.org/) for declarative code generation.

**Comment by paullatzelsperger** [comment]
There was a [discussion](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/246#discussioncomment-1743018) about Lombok, and we decided against it, because it modifies the AST and can potentially cause nasty problems when the compiler API changes. @jimmarino did a more detailed investigation if you're interested.

**Comment by jimmarino** [comment]
Yes, there are numerous issues with Lombok including the issue that Lombok makes use of internal, undocumented Java compiler APIs. This would prohibit us from supporting new versions of the Java if those APIs changed (like they did in Java 9) until Lombok releases a fix.

It also includes a significant number of extensions to the Java language that often result in difficult to understand code. 

Another issue is that Lombok would be unable to generate the style of Builders we have (which make extensive use of Jackson annotations and validation). In the end, it would not save us very much.
