### ISSUE TITLE
Refactor the module loading

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#469]
## Restructuring the `core` module

This will be refactored to contain only three sub-modules, those are: 
- `core:base`: will contain all modules currently located in `core`, except `transfer` and `contract`
- `core:contract`: contains all contract-management-related implementations
- `core:transfer`: contains all transfer-management-related implementations

## Dependency loading - requirements and preconditions

_Disclaimer: the term "dependency" here refers to the runtime-dependency expressed by `requires()` and `provides()` rather than Gradle dependencies._

The three `core` modules are added automatically according to the following rules, so we do not need to `require` them or any of their implementations explicitly. Should a module contain several submodules and/or extensions then the rules apply to all of them.
1. `core:base`: implicitly required by all other modules, that it is automatically loaded first during extension loading. One way of doing is would be to simply add a `requires` entry to all extensions on the classpath. 
1. `core:transfer`: implicitly required by all extensions (except other `core` extensions) as soon as it's on the classpath. That means that the `core:transfer` module is always loaded _after_ `core:base` and _before_ all other modules. Technically this could be achieved by adding a `required` entry to all modules (except core extensions) that have the `core:transfer` module on the classpath. So putting the `core:transfer` module on the classpath is enough, it never needs to be `"required"` explicitly.  
1. `core:contract`: implicitly required by all extensions that require the `core:transfer`, so the same mechanism can be applied there.

## Dependency loading - implementation considerations

- Establish a pattern where feature names must be accessible through constants, e.g. requiring the AssetIndex is done by adding `@Requires(AssetIndex.FEATURE)` to the extension.
- Introduce annotations: `requires()` and `provides()` methods will be substituted with annotations, `@Provides` and `@Requires` which take a list of Strings. This would give us the following advantages: 
  - can then be used to inspect dependencies without instantiating the extension class, 
  - perform some sort of dryrun or preflight check to detect dependency problems faster and without actually instantiating and initializing the extension
  - group dependencies together in another annotation, which is useful if the same set of dependencies are used together often, e.g. an extension for a specific AssetIndex implementation could be annotated with `@AssetExtension`, which be an alias for `@Provides(AssetIndex.FEATURE, AssetLoader.FEATURE, DataAddressResolver.FEATURE)`
  - dependency graphs could be generated as a means of documentation

- Introduce hierarchical features: feature names should be namespaced such that they express hierarchy. For example features within the `extension:foo` module have to be named `extension:foo:bar:stuff`, `extension:foo:baz:stuff`. Simply adding a dependency onto the parent feature, here `extension:foo`, would implicitly add depencies onto all "child" features "underneath" the `extension:foo` namespace. The parent feature would be synthetic, meaning we would never explicitly `@Provide` this, only the child features. This is a convenience functionality, as it reduces the amount of dependencies we need to express.

- Modules should expose their features (including parent features) through constants in an interface class in an SPI module, e.g. via `AssetIndex.FEATURE`. 

- remove the `LoadPhase` altogether

**Comment by ndr-brt** [comment]
Looks good!

A proposal: since we are introducing annotations, why not a `@Feature` annotation to be added on the interface representing the feature (e.g. `AssetIndex`)? This annotation would have as `value` the feature string.
This would avoid the need to remember to add the `FEATURE` constant into the interface and would permit the `@Requires` and `@Provides` to accept an array of class objects string, this would be more elegant and will give a stronger bound (no typo errors, no need to remember to add a `FEATURE` constant to a feature interface).

Another proposal: about the `policy-evaluator` module, since it's in the core and it will be moved into the `base` module. 
This module is a dependency of `spi` and, moving it into `core-base` will create a circular dependency between `spi` and `core-base`.
In my opinion, the `spi` module should be the root of the module tree, so that code should go into `spi` (or in a `policy-spi` module)

**Comment by paullatzelsperger** [comment]
- ad 1) let me look into that. We would then have something like `@Requires(AssetIndex.class)`, right? Not sure if this is more readable than `@Requires(AssetIndex.FEATURE)`
- ad 2) I agree, `spi` should not have any dependencies. the way I'd approach this is to rip apart the `spi` into several "sub"-spi's, like `contract-spi`, `transfer-spi`, etc. thus breaking the cyclic deps

**Comment by jimmarino** [comment]
I could go either way on 1. Regarding 2, the two policy modules should not have any dependencies on the runtime. This is so they can be embedded in other runtimes without dragging other things in, e.g. a validation tool or backend system that needs to perform evaluation. We can rename the module if that makes it clearer.

**Comment by ndr-brt** [comment]
1) yes, since that notation will miss the `FEATURE` word could be less understandable, but it will clearly define a what is a Feature and what does it need. Some validation could be done in the loading phase: e.g: check if the extension provides/requires something that it's an existing Feature and not a random string.

2) it could be called `policy-spi` and put at the same level of `spi` (that could be split in `base-spi`, `transfer-spi` and `contract-spi`)?

**Comment by jimmarino** [comment]
on 2,  +1. We can do that in the next step when we break up the SPI a reshuffle modules

**Comment by ndr-brt** [comment]
@paullatzelsperger I wasn't able toto review the PR in time... we didn't agreed on the `@Inject` annotation. 
I find it not so immediate to understand, especially because it works only on a `ServiceExtension` class, and that could lead to confusion (seems like we introduced a DI framework but in fact we didn't).
Personally, I prefer the classic programmatic way to get the services from the service context.

**Comment by paullatzelsperger** [comment]
This kind of evolved during the course of implementing the loading feature. The `@Inject` kills two birds with one stone: it defines the ordering during extension loading and it makes the code more succinct. 
Currently it is only enabled for `ServiceExtensions`, but we discussed over the holidays extending this toward other services, for which we will likely require very little modification. 

I'd say it's a module loading mechanism that uses dependency injection rather than a DI framework.

I'll bring back the `@Requires` annotation for use cases where people want to do it programmatically, that'll only be only a few lines of code and it will adhere to what was originally specified in the issue.

Another idea we had is doing auto-configuration.

Sorry about about not waiting for you, I thought you were out on holiday, and we wanted to get this in while as few people as possible were working on the code base concurrently.
