### ISSUE TITLE
Get all integration tests running again in Eclipse

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#54]

**Comment by beardyinc** [comment]
Most i-tests need some form of credentials for external systems (such as Azure, AWS,...), which need to be stored as repo secrets. Only Admins can add repo secrets, so we must request (temporary) admin status from EF and then add the secrets.

**Comment by mspiekermann** [comment]
related to #25

**Comment by paullatzelsperger** [comment]
Repo secrets are now in (#25), the integration test is also in, but we still need to fine-tune when they actually run:
- it **cannot** run in a fork, as the fork will likely not have the secrets
- it **cannot** run during PRs originating from a fork, because Github does not pass secrets to those PRs due to security concerns.

I think they should run before we actually merge a PR into `main`, and they should run on every push within the EDC upstream repo.

**Comment by mspiekermann** [comment]
so #215 and #216 failed again. can you check what might be the difference @ndr-brt?

**Comment by ndr-brt** [comment]
Looking at the history:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/workflows/integrationtests.yaml

Seems like they fails for reasons that don't depend from the code modification itself, a better analysis should be done
