### ISSUE TITLE
Integrate DID/SSI

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#56]
Sovereign identities can foster a sovereign data exchange. 
Beside the DAPS proposed by IDS today we'd like to prepare the EDC for integration of decentralized identifier / self-sovereign identity solutions.

**Comment by jimmarino** [comment]
From this branch:

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/gaiax-hackathon/registration-service

**Comment by beardyinc** [comment]
@jimmarino lets hold on here a bit, i'm currently cleaning that one up considerably. i'll post the relevant PR here when that's done.

**Comment by jimmarino** [comment]
@beardyinc OK cool. Should we close this out since there is already a PR for this work?

**Comment by beardyinc** [comment]
we can either close it or link it to #58

**Comment by schanzen** [comment]
Hey (DAPS operator here). I would just like to point two issues that are also related to the changes in #58:

1. A self-signed JWT is NOT a verifiable credential as stated in the code. If you want to make use of VCs in JWTs, you probably want to put a Verifiable Presentation (VP) derived from a VC into the JWT. See also https://www.w3.org/TR/vc-data-model/#json-web-token. Which brings us to:
2. You will not _replace_ the DAPS with a self-signed DAT. Why should connectors trust the contents? You will still need a DAPS which issues VCs (see also https://www.w3.org/TR/vc-data-model/#json-web-token) which a connector can then use to generate a self-signed JWT containing the VP.

my 2 cents.

**Comment by jimmarino** [comment]
Hi,

Thanks for the feedback. To be clear, our approach with federated identity is to use a self-signed token with verifiable presentations and the ability to obtain additional verifiable credentials for a client via an Identity Hub.

In a DID-based system, it is possible to introduce multiple trust anchors, which allow providers to verify JWT claims and verifiable credentials obtained from an Identity Hub. 

One of the reasons we are investigating federated identities is because some of our use cases stipulate that no central authority be required to anchor identities in a dataspace. Also, we want to remove single points of failure, which many OAuth2-based implementations are susceptible to.  

Of course, users can choose which identity model suits their needs with the EDC. There is an OAiuth2 implementation that can be cleanly swapped with the distributed identity implementation (or implementations if people want to support multiple ways of achieving federated identity).

For more details on the approach to federated identity we are pursuing, see the following specs. We're happy to answer questions as they arise. 

https://identity.foundation/identity-hub/spec/
https://identity.foundation/sidetree/spec/
https://w3c-ccg.github.io/did-method-web/
https://www.w3.org/TR/did-core/

**Comment by schanzen** [comment]
> Hi,
> 
> Thanks for the feedback. To be clear, our approach with federated identity is to use a self-signed token with verifiable presentations and the ability to obtain additional verifiable credentials for a client via an Identity Hub.

I was commenting on the code, which does not implement what you imply.

> 
> In a DID-based system, it is possible to introduce multiple trust anchors, which allow providers to verify JWT claims and verifiable credentials obtained from an Identity Hub.

You can always introduce multiple trust anchors even now.
The trust is essentially established at the discretion of the callee (the endpoint verifying the DAT).
Whichever trust sources you have configured there are trusted. Nothing is keeping you from trusting multiple different DAPS instances.
Trust does not come form the ether of a ledger or the DID spec. It comes from specific configurations on the endpoint.

> 
> One of the reasons we are investigating federated identities is because some of our use cases stipulate that no central authority be required to anchor identities in a dataspace. Also, we want to remove single points of failure, which many OAuth2-based implementations are susceptible to.

But you will not solve this issue.
I think there is a misunderstanding here on what the DAPS is for. It is not relevant which standards you use or architecture you build it on.
If you have a single point of trust you have single point of failure. It does not matter which format of token you choose.
Verifiable Credentials also expire. So it does not matter if you use OAuth or any other mechanism to retrieve them.

> 
> Of course, users can choose which identity model suits their needs with the EDC. There is an OAiuth2 implementation that can be cleanly swapped with the distributed identity implementation (or implementations if people want to support multiple ways of achieving federated identity).

You are conflating protocol standards with trust management.
SSI does not change the trust model. It simply moves responsibility of handling credentials to the credential holder and limits interaction with IdPs. Also, formats like VCs offer flexibility wrt PABCs for selective disclosure.

Note I am not arguing against the use of VCs and SSI. I am simply pointing out that by doing so you will not achieve the goal which is claimed in the OP of this issue. You will still have issuers which are essentially DAPS instances. Whether you call them DAPS instances or not is irrelevant. Those issuers will have to be configured as trust anchors somehow on the endpoints.

> 
> For more details on the approach to federated identity we are pursuing, see the following specs. We're happy to answer questions as they arise.
> 
> https://identity.foundation/identity-hub/spec/ https://identity.foundation/sidetree/spec/ https://w3c-ccg.github.io/did-method-web/ https://www.w3.org/TR/did-core/

As you can see from the link I posted, the DID efforts seem to be going nowhere for now.
Committing on anything beyond VCs and possibly SIOP seems like a gamble.

BR

**Comment by jimmarino** [comment]
> > Hi,
> > Thanks for the feedback. To be clear, our approach with federated identity is to use a self-signed token with verifiable presentations and the ability to obtain additional verifiable credentials for a client via an Identity Hub.
> 
> I was commenting on the code, which does not implement what you imply.

Could you point out where that is the case? There are still parts of the code that need to be completed and filled out (it is still experimental), but I don't see how the existing code inhibits our goals.

> 
> > In a DID-based system, it is possible to introduce multiple trust anchors, which allow providers to verify JWT claims and verifiable credentials obtained from an Identity Hub.
> 
> You can always introduce multiple trust anchors even now. The trust is essentially established at the discretion of the callee (the endpoint verifying the DAT). Whichever trust sources you have configured there are trusted. Nothing is keeping you from trusting multiple different DAPS instances. Trust does not come form the ether of a ledger or the DID spec. It comes from specific configurations on the endpoint.

I think we should be careful here:.I didn't say that it is impossible to introduce multiple trust anchors with existing security infrastructure. I said it is possible to so with DID-based systems (and arguably in a more flexible way, but that is a separate discussion).

> 
> > One of the reasons we are investigating federated identities is because some of our use cases stipulate that no central authority be required to anchor identities in a dataspace. Also, we want to remove single points of failure, which many OAuth2-based implementations are susceptible to.
> 
> But you will not solve this issue. I think there is a misunderstanding here on what the DAPS is for. It is not relevant which standards you use or architecture you build it on. If you have a single point of trust you have single point of failure. It does not matter which format of token you choose. Verifiable Credentials also expire. So it does not matter if you use OAuth or any other mechanism to retrieve them.

I am not sure I follow why we will not solve the issue. 

We should be careful about terms here as well. Some of our use cases require that a central authority must not be needed to anchor identities. This means participants must be in control of their identities. This can be achieved by anchoring a DID in a DLT or using another mechanism such as web DIDs, in combination with an Identity Hub. My understanding is that no matter how many "DAPS" systems there are, there is always the possibility that *your* (central) identity provider can "pull the plug" and invalidate your identity. Having multiple (central) identity providers does not solve that problem.    

My other point was that many (not all) OAuth2 implementations are susceptible to being single-points of failure. Again, it doesn't matter how many identity providers you have in a system. If one of the providers goes down, a significant portion of the dataspace will be rendered inoperable. Achieving reliability in this model is difficult, since it requires features such as geographic replication and fault-tolerance that few infrastructures support. 

In our approach these risks are mitigated by the ubiquity of DLT technologies or having each participant host their own DID document via web DIDs.

> 
> > Of course, users can choose which identity model suits their needs with the EDC. There is an OAiuth2 implementation that can be cleanly swapped with the distributed identity implementation (or implementations if people want to support multiple ways of achieving federated identity).
> 
> You are conflating protocol standards with trust management. SSI does not change the trust model. It simply moves responsibility of handling credentials to the credential holder and limits interaction with IdPs. Also, formats like VCs offer flexibility wrt PABCs for selective disclosure.

I don't how my previous statement conflates protocol standards and trust management. I was saying that the EDC architecture allows for choice. Users can choose an OAuth2 model, DAPs, federated identity, or another approach that fits their use case if they elect to implement the appropriate extensibility points.

FWIW, Identity Hubs are designed to support selective disclosure. 

> 
> Note I am not arguing against the use of VCs and SSI. I am simply pointing out that by doing so you will not achieve the goal which is claimed in the OP of this issue. You will still have issuers which are essentially DAPS instances. Whether you call them DAPS instances or not is irrelevant. Those issuers will have to be configured as trust anchors somehow on the endpoints.

I don't think anyone associated with this PR is claiming we are attempting to remove trust anchors. We're actually trying to do the opposite: enable a flexible and robust way for participants to choose which trust anchors they want to use.

In my mind DAPS is basically an implementation. I don't think we should use the term interchangeably with "identity provider" or "trust anchor". In any event, the key thing we would like to achieve with EDC is choice. A one-size-fits-all approach to identity is not going to work for our users given their different use cases and requirements. IMO, we need to adopt an open architecture to accommodate this reality.

 
> 
> > For more details on the approach to federated identity we are pursuing, see the following specs. We're happy to answer questions as they arise.
> > https://identity.foundation/identity-hub/spec/ https://identity.foundation/sidetree/spec/ https://w3c-ccg.github.io/did-method-web/ https://www.w3.org/TR/did-core/
> 
> As you can see from the link I posted, the DID efforts seem to be going nowhere for now. Committing on anything beyond VCs and possibly SIOP seems like a gamble.
> 
> BR

I and others have a different view on this. The good thing is that the EDC architecture is flexible enough for people to choose which extensions and identity implementations best fit their needs.

**Comment by jimmarino** [comment]
Closing as this work has been integrated.
