### ISSUE TITLE
spi folder potentially contains classes/packages not directly involved in SPI loading

### ISSUE THREAD

**Issue by softabout** [eclipse-dataspaceconnector/DataSpaceConnector#65]
The directory/module "spi" should only contain interfaces (and the classes used to define these interfaces) that define the types of service provider interfaces (SPIs) which are loaded by java.util.ServiceLoader.
Currently these are:
- MonitorExtension
- ServiceExtension
- VaultExtension

and their base interfaces.

The following packages contain interfaces which are not directly loaded by java.util.ServiceLoader, but by an extension/spi implementation of org.eclipse.dataspaceconnector.system.ServiceExtension:
- policy (ServiceExtension)
- transfer (ServiceExtension)
- protocol (ServiceExtension)

Suggestion

- separate plain SPI interfaces (that define functionality loaded by java.util.ServiceLoader) from service interfaces introduced and registered by implementations of org.eclipse.dataspaceconnector.spi.system.ServiceExtension. 

<sub> Helmut Pfister <helmut.pfister@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by jimmarino** [comment]
Hi Helmut,

The original id of the SPI was to include all interfaces required to implement an extension, which would include a combination of a ServiceExtension and services provided to the runtime. In other words, both interfaces related to the JDK ServiceLoader mechanism (which is the basis of EDC extensibility) as well as interfaces for runtime services.

The benefit of having these in one module is that there is one place to look for extension points. Also, I'm not sure there is a major functional distinction between service loader interfaces and service interfaces that merits different modules as opposed to different packages.

I'm open to separating these into modules if there is a major functional difference. What do others think?

**Comment by MoritzKeppler** [comment]
I like the idea to make it more obvious how SPI, extensions and services play together: we load extensions via SPI, those extension can register one or more services at the central registry, potentially based on interfaces defined in the SPI module. But extensions can also lookup other services and register things there (e.g. provisioners).
What about moving all interfaces that are looked up via  Java SPI into a package called spi and rename the whole module to something like "interfaces"/"api"/"core-api", ...
Maybe we also need to improve the documentation (README/onboarding/in Java Code) to clarify what should be used in which case.
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
I don't think the module is really an API since an API is an ingress into the system and could be confused with other modules that do this. I'm not keen on "interfaces" either since that is ambiguous.

I still think "SPI" captures the intent since it is an EDC "Service Provider Interface" - i.e. the interfaces providers need to implement to contribute a service to the runtime. Basically, it's an analog to the Java SPI (which it uses).

Could this be solved by better documentation? The system package already contains the interface types looked up by the ServiceLoader, which separates them from the other interfaces. Placing those in another module IMO would just increase the complexity for extenders since they would need to look into two separate modules.
