### ISSUE TITLE
Contribution: evaluate adding PR description templates

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#698]
PRs should have a minimum description stating _WHAT_ has been changed and perhaps even _WHY_ the change was necessary. This will help reviewers greatly. Also, if there is a related issue, the PR should link to that issue. 

This issue deals with investigating whether those templates can be provided automatically, which seems to be the case according to the links below.

Once a suitable template has been created, the `contributing.md` file should document it as well.

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
- https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/

**Comment by jimmarino** [comment]
Having a template would help reviews a lot. With the aim of keeping them simple and quick, I think the template should include and agree it should include:

1. The type of change, e.g. bug fix, new feature, cosmetic (no code changes), etc.
2. Specifically what was changed. This should be clear and detailed to avoid reviewers having to comb through the PR before they understand its scope.
3. If not a bug, why the change was necessary (Motivation)
4. Link to an issue that explains the change in more detail. If the issue is detailed, step 2 can be shortened.

**Comment by florianrusch-zf** [comment]
Another good example could be the k8s PR template: https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1

If you take a look at the source code, you will see that they have added some markdown/html comments with tips and so on to guide the author.
