### ISSUE TITLE
Discuss and improve extension-dependency naming scheme

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#79]
Lets see if we can come up with a consistent and intuitive way to express dependencies (i.e. the `requires()` and `provides()`) that is consistent over all modules.

There are a few suggestions:
1) fully qualified classname. Can be problematic when one extension provides several features and when several modules provide the same feature. 
2) a hierarchical namespace like `edc:<feature>[:<subfeature>]`, e.g. `edc:policy-registry` or `edc:communication:http-client`

We should also think about defining constants for that in the interface class, e.g. in `PolicyRegistry.java`

**Comment by jimmarino** [comment]
I like the approach in 2. IMO the problem with 1 is that it ties dependencies to specific implementation classes. Instead, they should be a symbolic name. For example, one extension may provide 2 or more features that clients depend on.

The advantage of 2 the way you defined it is the symbolic name can also be a URN and we can reserve "edc" to avoid clashes.

**Comment by DominikPinsel** [comment]
Maybe another, complete different, approach. Wouldn't a dependency injection framework solve this problem, too? Because the framework should be able to resolve dependencies on it's own, so it won't be necessary to track them manually in an array.
It also would simplify other things, like the primordial load phase. And using DI frameworks is somewhat state of the art, so every developer knows how they work without reading any documentation.

**Comment by jimmarino** [comment]
There were a number of reasons why we chose not to use a DI framework such as Spring (version clashing, a gazillion dependencies, abstractions on abstractions, non-standard APIs, keeping the connector codebase small so its security footprint is manageable, etc.). I think these are fair trade-offs for an application but they become problematic for low-level code that has to be deployed in varied environments.
  
If we were to go down this route, it would entail a complete re-write of the codebase...I'd prefer not to do that.
