### ISSUE TITLE
DataManagementApi: implement soft-delete

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#814]
All relevant entities mentioned in #811 should have a `deleted` field marking them such. 
Deleting an entity will then set the flag to `true` instead of purging it from the store, causing all queries to not include that entity anymore.

This involves a significant amount of work:
- introduce a `Deletable` interface providing the `isDeleted()` flag, which all aforementioned entities/business-objects must implement
- adapt all data stores and the queries inside them to not include entities marked as deleted.
- adapt and extend all tests
- possibly add queries to all stores allowing to specifically query deleted items

_This is not yet ready for development - further architecting is required!_

**Comment by ndr-brt** [comment]
Question. It's clear that the `query(QuerySpec)` method should not return the deleted object (unless explicitly specified e.g. through a query param), but what about the `findById(String)`?
Probably it will return the entity that will be marked as deleted. This question is to understand how to handle deletion. E.g. an asset that is referenced in a contract agreement could be soft deleted? I think so, because from the deletion onwards it won't be accessible anymore from any query, but the agreement will keep to be valid.
Otherwise the Asset could not be deleted until the agreement is still valid (or not deleted).
