### ISSUE TITLE
DataPlaneFramework: add Micrometer instrumentation

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#837]
For a holistic end-to-end picture we need to add OpenTelemetry and Micrometer instrumentation to it.
As those two topics are closely related they can be done in the same issue.

**Comment by bscholtes1A** [comment]
Hi @marcgs 
is there something to be implemented on top of your PR #1162 for that issue to be closed?

**Comment by marcgs** [comment]
> Hi @marcgs is there something to be implemented on top of your PR #1162 for that issue to be closed?

My PR took care of the distributed tracing part with Open Telemetry only. Metrics with Micrometer are mostly reused from what is already available from EDC since #637 . We could still add instrumentation of asynchronous processing in [DataPlaneManagerImpl](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImpl.java#L120) to see execution times for each loop  if relevant (would require rework of the looping logic). WDYT @paullatzelsperger ?

**Comment by paullatzelsperger** [comment]
I haven't looked at the code closely, but if we instrument it, we should instrument it everywhere.

**Comment by bscholtes1A** [comment]
Hi @marcgs @paullatzelsperger 
coming back to this one. 

What is then still required to close this one? (as this is planned for milestone 4)
Only instrumentation of the parallel processing in DataPlaneManagerImpl? If yes I can take care of that

**Comment by paullatzelsperger** [comment]
@bscholtes1A if you could do that, that would be great. the CSE crew is out this week.

**Comment by paullatzelsperger** [comment]
@bscholtes1A any updates? is there more work necessary, or is it done?
