### ISSUE TITLE
CI: Separate build tasks and test tasks

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#840]
In order to reduce build times and increase repeatability, we should restructure our CI pipeline so that compiling/assembling the artifacts is done separately in a preliminary step. All test jobs (unit, integration, etc.) and verification jobs (checkstyle, codeql) should run re-using those artifacts.

**Comment by ndr-brt** [comment]
I agree with the need to restructure our pipelines, and I'm also a big fan of "build once, test/deploy many" pattern, but I don't know if it's so practical on Github Actions, because after the build we would need to pack all the output and upload as artifact to make it available for the other jobs, unfortunately the output of the build project of the EDC compressed in a tar file currently is about 2GB, and it will take a lot of time to upload/download it, so at the end there would be no time savings.
(tested here: https://github.com/ndr-brt/DataSpaceConnector/actions/runs/1963366097)

**Comment by paullatzelsperger** [comment]
we'd only need the artifacts between _workflows_ though, right? afaik jobs share the same filesystem

**Comment by ndr-brt** [comment]
Nope, steps share the same filesystem, but jobs don't (as they by default run in parallel)

**Comment by ndr-brt** [comment]
This can be closed too, as a lot of work has been done on job separation.
