### ISSUE TITLE
CosmosDB Emulator failed to reach running state

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#845]
# Bug Report

## Describe the Bug
During CosmosDb-Integration tests the emulator fails to reach the "running" state within 1200 seconds

### Expected Behavior
it reaches the "running" state

### Observed Behavior
[see this CI run](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5460040988?check_suite_focus=true)

## Steps To Reproduce
not reproducible, seems to happen randomly

## Context Information
n/a

## Detailed Description
n/a

**Comment by paullatzelsperger** [comment]
@algattik @ndr-brt I took the liberty of assigning this directly to you since you worked in this area in the past.

**Comment by algattik** [comment]
Out of the 25 last builds, 5 have failed with either a timeout starting the emulator, or a request timeout running the test.

For the latter, the case could be made that any code that runs against Cosmos DB should have retry logic built-in, since the transient failures could happen on cloud too.

Following up internally.

**Comment by paullatzelsperger** [comment]
> that any code that runs against Cosmos DB should have retry logic built-in

All of the CosmosDB-based implementations have a `RetryPolicy` (jodah.failsafe), the `CosmosTransferProcessStore` even distinguishes between general retry and a retry due to rate limiting, as we hit rate limits in the past. 

Looks like it's mostly failures to _start_ the emulator, rather than _communicate_ with it, no?

Maybe running the entire test containerized might be worth trying out?

**Comment by algattik** [comment]
Of the 5 runs that failed today:
- Twice `CosmosTransferProcessStoreIntegrationTest > invokeStoreProcedure` this test code has no retry policy
- Once `CosmosAssetIndexIntegrationTest > queryAssets_selectAll` this test code has a default retry policy, which retries 3 times with no delay. Given the emulator probably fails because of too high CPU utilisation, perhaps (maybe!) a delay would help
- Twice `Failed to start emulator The emulator failed to reach Running status within 1200 seconds`

I'm reaching out internally to try to find solutions, but perhaps the fallback will be to test on cloud instead.

**Comment by ndr-brt** [comment]
Seems like it's failing a lot: 
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/workflows/integrationtests.yaml

In my opinion we should go back and test it on cloud on the CI until the emulator will reach a stable state.

**Comment by Izzzu** [comment]
> Seems like it's failing a lot: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/workflows/integrationtests.yaml
> 
> In my opinion we should go back and test it on cloud on the CI until the emulator will reach a stable state.

@ndr-brt We started working on it, will raise PR soon
