### ISSUE TITLE
Milestone 3 Policy Enhancements 

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#855]
## Overview
                            
This issue serves as an umbrella for Milestone 3 (M3) policy-related work. 

### Policy
A policy contains 0..N *Rules*, which are *Duties*, *Obligations*, or *Permissions*. Policies are evaluated at runtime.

### Policy Scope
A policy scope defines a __*visibility*__ and __*semantic*__ boundary for policy rules. Scopes are hierarchical and expressed using dot notation. For example, `provision.verify` and `provision.execution` are child scopes of `provision`. If a rule is visible in a given scope, it will be included in policy evaluations for that scope; otherwise, it will be omitted. Policy rule semantics are implemented at runtime by __rule and constraint functions__ (described below).

### Rule Binding
A rule binding makes a rule type visible in a policy scope. Since scopes are hierarchical, a binding that specifies a parent context will result in the rule type being visible in child scopes. The `*` wildcard is used to denote all scopes. A rule binding specifies one rule type and one scope. Rule types may be bound to different scopes using multiple bindings.  

### Rule and Constraint Functions
Rule and constraint functions are registered for a policy scope and are code that is executed at runtime during policy evaluation. Rule and constraint functions implement rule semantics.

## Example Use Cases

Consider the following geospatial rule (GS-1):

> Asset content (data) must remain in EU-based compute environments. 

The above geospatial rule type is bound to multiple scopes and has different semantics in each scope.  

#### Authorization Scope
The authorization scope is evaluated when accessing an asset, for example, when requesting a data transfer. The GS-1 rule type is bound to this scope (`authorization`), and its semantic is to check that a claim exists in the auth token the consuming participant includes in its data transfer request. This semantic is implemented as a constraint function registered with the runtime policy engine.   

#### Provision Scope
The policy for the provision scope is evaluated at various points during runtime operation. The `provision.verify` child scope is engaged when requesting a data transfer (note that this currently does not exist and will be implemented for M3). GS-1 is also bound to this scope, but its semantic will be different. The semantic will ensure that the transferred data can be placed in EU-based storage on the consumer. On the provider, GS-1 is not bound.

Consider another rule (PARTNER-1):

> Asset content (data) can only be accessed by an active business partner.

#### Authorization Scope
The PARTNER-1 rule type is bound to this scope, and its semantic is to verify a claim contained in the consuming participant's auth token against a backend system.

#### Provision Scope
The PARTNER-1 rule type is not bound to this scope.

Finally, a rule specifying usage limitation for API access (API-1):

> An API (represented as an asset) can only be accessed N times.

In this case, access to the API is mediated by an EDC Data Plane Framework Server (DPF). 

#### Authorization Scope
The API-1 rule type is not bound to this scope since the asset is visible to the consuming participant.

#### DPF Request Scope
The DPF request scope is engaged when issuing an API request against the Data Plane Server. The API-1 rule type is bound to this scope, and its semantic is to verify and count the number of requests made by a consuming participant.

## Work Items

This section serves as a pointer to sub-issues that address specific policy work items for M3.

### Policy Scopes
The existing `PolicyEngine` will be enhanced to support scopes. See #856. 

### Policy and Rule endpoints
Support for evaluating entire policies or specific rules using HTTP endpoints will be added (TBD). Special consideration will need to be made for performance-sensitive code paths. See #857.  

### Policy Evaluation Points (PEPs)
Numerous runtime policy evaluation points will be added, for example, to the DPF and provisioning subsystem (TBD). See #858.

**Comment by MoritzKeppler** [comment]
like the idea, thanks! some questions that came to my mind:
The scopes of a rule are defined a priori, right? E.g. a geospatial rule will always be applied to "provision" and "authorization" scope. What about a (completely theoretical!) case, that during provisioning access rules need to be configured (e.g. provision access to an API Gateway including an n-time access limitation)?
Do all components involved in one of the steps (e.g. all provisioners in a data transfer process) have to enforce the rules?

**Comment by jimmarino** [comment]
Hi @MoritzKeppler. +1 on the idea of a priori bindings but I think the core runtime should not have knowledge of this. A priori bindings can be added by an extension (which in turn could be triggered by configuration). 

For example, the EDC could define a set of policy rule types but not their implementation, e.g. "geospatial constraint". Some of these rule types could have IDC analogs and some rule types could be supported by various extensions like object storage. The task of enabling these rules in a runtime could be to add configuration, which triggers rule bindings for various scopes.

What do you think?

**Comment by jimmarino** [comment]
Regarding the theoretical case, let's take the n-time access limitation and identify the rule type as "nt-al". Let's say that there are two "protocols" supported by an EDC deployment for data transfer, the API Gateway, and push-based object storage.  Let's also say nt-al is not supported for push-based object storage. Finally, let's assume there will be a policy evaluation point (PEP) and scope to check these policies when a data transfer request is made.

This leads to two scenarios:

1. A request is made for an asset that has an nt-al rule and is only available via the API gateway.
2. A request is made for an asset available via object storage. It has no nt-al rule.

For the PEP in Scenario 1 to evaluate, the EDC deployment will need to have a Policy function that satisfies the nt-al rule when the API Gateway protocol is used. From an end-user perspective, this could be handled by having a mechanism that accepts user configuration, "the API Gateway data transfer protocol supports the nt-al rule". Internally, this would involve engaging a Policy function when the PEP is fired based on the protocol requested.

Further, during provisioning, the API gateway would need to be configured to implement the nt-al rule. This can be handled by a combination of a Resource Manifest generator and Provisioner, both of which have access to the policy for that scope.

For the PEP in Scenario 2, the nt-al rule is no present and the transfer process will proceed accordingly.

Does this aign with what you are thinking?

**Comment by jimmarino** [comment]
Started associated DR: #892.

**Comment by juliapampus** [comment]
Some comments from my side:

First of all, regarding the term "policy evaluation point". I understood from your descriptions (already commented in #857) that you define a PEP different from other implementations and specifications (see e.g. the [XACML architecture](https://www.researchgate.net/figure/Data-Flow-Diagram-for-XACML-Architecture_fig1_221521494) as it covers somehow the decision taking and evaluation of context information. That is in my understanding a PDP and PIP. Therefore, maybe we either need to align to existing specifications, or create a document that details our understanding - as this will, for sure, cause misunderstandings.

Second topic: Why do we need policy scopes? I know you could not attend the usage control workshop last week. There, we discussed this point in some detail as Paul introduced your thoughts of interpreting policies according to context information.

I cite the document of your PR #892: 
> Policy rules may only be applicable in certain runtime contexts. For example, the following policy rule: "Data must be anonymized." That rule may be applicable to policy evaluation when a resource is provisioned but it may bot be applicable during data transfer. There must be a way to specify when a rule type is applicable during runtime evaluation.

Information like this should be expressable in ODRL unambiguously by using the right targets and actions. In this context, a contract could contain a rule pointing to the asset and defining constraints for action `USE` and a rule pointing to the asset and defining constraints for an action `PROVISION`. If we identify actions and terms that are not covered by ODRL, we could extend this by implementing some kind of ODRL profile, couldn't we? Instead of implementing non-mappable EDC-specific solutions.

In general, I think it would be nice to first collect requirements (referring to [this](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/878) discussion and the on-going UC workshop series) and derive a stable and well-structured modularization of the policy engine, that could be extended for complex use cases later. As for now, I don't see the need for those complex use cases you take as a discussion bases, if they are written down nowhere.

**Comment by jimmarino** [comment]
Hi @juliapampus

Thanks for the feedback!

Regarding PEP vs. PIP and PDP, I believe there is value in keeping the distinction between the three as XACML does. Instead of Policy “Evaluation” Point, I’m happy to call it as XACML does, Policy “Enforcement” Point, or even something else.  

On the use of ODRL “action” to implement the concept of “scopes,” I think doing so would overload the former in a way that won’t achieve what we need. In ODRL, an action indicates an operation on an asset. The use cases I outlined aren’t operations on assets (geospatial rules, etc.). 

More fundamentally, I don’t think the visibility and semantic boundaries of rule evaluation in a runtime should be expressed as part of a policy. They are separate concerns. A policy is a collection of _**abstract**_ rules (not necessarily tied to an asset). Those rules may imply semantics, but they are abstract. For example, a rule that constrains data to “Europe” does not specify how that is done, which is concrete “implementation” semantics. A runtime my have code that selects an AWS region for its implementation. Or, a runtime may do nothing if it is deployed in a European on-premise datacenter with collocated storage. 

In a dataspace, all exchanged policies must be abstract in this sense for interoperability. Participants agree on the abstract semantics of policies, but they are not concerned with how they are specifically achieved. In line with this, it would not make sense to advertise concrete semantics as an action to other participants in a policy expression. 

If we mix these concepts (abstract policy and implementation), we will also run into other problems. For example, policies are immutable, and rule types can be referred to by many policies. If we include implementation semantics in those types, we will tie them to specific details of EDC deployments. Rules and policies would not be reusable across EDC deployments, and every time a deployment changes, new policies would need to be created.

Those are the main reasons I think we need to introduce scopes and the concept of “rule bindings.” They allow policies to be expressed independently of implementation details.

Regarding the use cases I mentioned, my employer has these requirements. I’m happy to drill down into more detail, but they are relatively straightforward as outlined in the issues. Also, the changes needed to support these cases are relatively constrained and do not impact any aspects of the current architecture. When we receive additional use cases from the workshops, we can also accommodate those as well.

**Comment by juliapampus** [comment]
> The use cases I outlined aren’t operations on assets (geospatial rules, etc.).

> Regarding the use cases I mentioned, my employer has these requirements. I’m happy to drill down into more detail, but they are relatively straightforward as outlined in the issues.

Could you maybe add those use cases to [this discussion](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/878)? Not in a way that reveals corporate strategies, but abstract enough to be helpful as a discussion basis. It is important to have such a requirement overview to maybe also see what use cases and projects match or overlap, and to track why we focused on what policy.

**Comment by juliapampus** [comment]
@jimmarino Thanks for the detailed answer! I just had another look at the other issues and the PR, and I think I can follow your thoughts - sounds reasonable for me. Still, I have some questions, I hope that's okay. 

Policy Scopes should help to classify policies to being able to use this additional information for implementation purposes, right? How does this scope now fits to a policy expressed in ODRL? Do we decouple from it and define an "EDC policy" that has an ODRL part and a supplementary policy scope? I am asking because I could not find the term `RuleBinding` (you mentioned in #856) in the context of ODRL. And if so, is this then a hidden information just added on the provider side? What about use cases that maybe need a `RuleBinding` on the consumer side, but defined from a data provider? Is this imaginable and how would this be implemented? Does this imply that the "EDC policy" or modified ODRL policy is included in the transferred contract/policy during the negotiation phase? And how would this align with ODRL and IDS as this would be nevertheless a custom expression? 

Lastly, are you referring to a standard by defining those policy scopes (you mentioned some examples in your pull request)? If not, does it make sense to defined some basic terms? However, we would need requirements for this to cover all needs that do not bring fundamental changes in some weeks.

**Comment by jimmarino** [comment]
@juliapampus all good questions, I'll try and break those down and answer them.

On requirements, sure, I will add those to the discussion.

Yes, scope bindings are a runtime implementation concept. They are a way to make an "abstract" model concrete at deployment time. As you said, policy bindings are completely decoupled from the policy definition. Instead, a binding associates a rule *type* with a scope. So, a rule type may be bound to multiple scopes. 

This decoupling has two aspects. First, in an organization, there are two roles: a data officer and an EDC developer. The data officer will define policies from a set of supported rules (rule types). The data officer does not need to know about how the policy they define maps to executable code at runtime. The EDC developer implements support for rule types (or configures "out-of-the-box" ones). This latter practice may be done by writing code and "mapping" that code to execution points in the runtime. Conversely, the EDC developer does not need to know about the specific policies defined by the data officer.

The second aspect is policy exchanged between two organizations. There is no need to convey binding or scope information 
since it is an implementation detail. It's similar to the situation where an organization does not care which Connector implementation another organization runs. It only cares about the other connector's supported policies and credentials.

Given this, bindings should not be expressed in ODRL or concern IDS. They exist as independent constructs alongside policy. 

XACML has a concept of scopes but it is different from the concept here. I'm not sure there is a direct analog but the concept of binding abstract models to concrete implementations is pretty common, e.g. WSDL bindings and SCA policy intents.

Let me know if this answers your questions.
