### ISSUE TITLE
Tests: improve experience

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#994]
# Feature Request

The experience of running tests locally on developer machines should be improved in the following aspects:
- the amount of log output should be significantly reduced. No test should output anything to the console by default. [Optional]: create a commandline parameter that controls the log output, something like a "verbose" flag.
- Failing tests should be clearly identifiable. Currently it is very cumbersome to scroll hundreds of lines up until the failing test comes into view. Once the first aspect is done, this should already be improved significantly, but further improvements may be in order, such as a test summary.
- Reduce the set of tests that are run by `./gradlew clean test` (see issue #819): by default only unit tests should be run. 

## Which Areas Would Be Affected?
build, unit tests

## Why Is the Feature Desired?
Building the entire code base (and thus running tests) is now really convoluted, and it needs to be cleaned up.

## Solution Proposal
Mitigations to this problem may include (but are not limited to):
- prohibit using the `ConsoleMonitor` in tests. We may even be able to verify this with a [checkstyle rule](https://checkstyle.sourceforge.io/config_regexp.html)
- in integration tests, that spin up EDC extensions, we need to also replace the `ConsoleMonitor` with a dummy one, or at the very least set its level to `SEVERE`.
- avoid `System.out.println` (obviously)

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
> the amount of log output should be significantly reduced. No test should output anything to the console by default. [Optional]: create a commandline parameter that controls the log output, something like a "verbose" flag.

In my opinion this should be seen from a different perspective: it would be better to have tests that can log to console by default and to have the possibility to hush them with a flag.

This because it should be straightforward from a developer perspective to have logs printed by default when they are launched from the IDE, especially on the `system` ones (the unit ones probably won't never log to console as the mocked monitor is being used).

> Failing tests should be clearly identifiable. Currently it is very cumbersome to scroll hundreds of lines up until the failing test comes into view. Once the first aspect is done, this should already be improved significantly, but further improvements may be in order, such as a test summary.

this is a gradle issue, on stackoverflow there are a lot of ways on how to get better test report on console output (like https://stackoverflow.com/a/43936442)

> Reduce the set of tests that are run by ./gradlew clean test (see issue https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/819): by default only unit tests should be run.

if this is needed to have faster builds, probably will be better to separate "fast test" from "slow test", monitor test duration, tackle on slower tests and stuff like this.
starting running `system tests` separately from the others could be a first good step.

**Comment by algattik** [comment]
#1018 implements the first part of this issue. Note that there is no need to prohibit usage of STDOUT, since the gradle test plugin intercepts it (and displays it optionally, based on verbosity flag).

For the second part of this issue (Reduce the set of tests that are run by `gradlew test`), we will provide this in our PR for #819.
